import { config } from "./config";
const API="https://classroom.googleapis.com/v1";
async function api<T>(token:string,path:string,init?:RequestInit):Promise<T>{const r=await fetch(`${API}${path}`,{...init,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json",...(init?.headers??{})},cache:"no-store"});if(!r.ok)throw new Error(`classroom_api_error:${r.status}:${await r.text()}`);if(r.status===204)return undefined as T;return r.json();}
export function assertAllowedCourse(courseId:string){const allowed=config.allowedCourseIds;if(allowed.length&&!allowed.includes(courseId))throw new Error("course_not_allowed");}
export async function listCourses(token:string){const all:any[]=[];let pageToken:string|undefined;do{const q=new URLSearchParams({teacherId:"me",courseStates:"ACTIVE",pageSize:"100"});if(pageToken)q.set("pageToken",pageToken);const d=await api<any>(token,`/courses?${q}`);all.push(...(d.courses??[]));pageToken=d.nextPageToken;}while(pageToken);const allowed=config.allowedCourseIds;return allowed.length?all.filter(c=>allowed.includes(c.id)):all;}
export async function listTopics(token:string,courseId:string){assertAllowedCourse(courseId);const d=await api<any>(token,`/courses/${encodeURIComponent(courseId)}/topics?pageSize=100`);return d.topic??[];}
export async function createTopic(token:string,courseId:string,name:string){assertAllowedCourse(courseId);return api<any>(token,`/courses/${encodeURIComponent(courseId)}/topics`,{method:"POST",body:JSON.stringify({name})});}
function links(v?:{url:string;title?:string}[]){return(v??[]).map(x=>({link:{url:x.url,title:x.title}}));}
export async function listCourseWork(token:string,courseId:string){assertAllowedCourse(courseId);const d=await api<any>(token,`/courses/${encodeURIComponent(courseId)}/courseWork?pageSize=100`);return d.courseWork??[];}
export async function createAssignment(token:string,courseId:string,input:any){assertAllowedCourse(courseId);const body:any={title:input.title,description:input.description,workType:"ASSIGNMENT",state:input.state??"DRAFT",topicId:input.topicId,maxPoints:input.maxPoints,materials:links(input.links),dueDate:input.dueDate,dueTime:input.dueTime,scheduledTime:input.scheduledTime};Object.keys(body).forEach(k=>body[k]===undefined&&delete body[k]);return api<any>(token,`/courses/${encodeURIComponent(courseId)}/courseWork`,{method:"POST",body:JSON.stringify(body)});}
export async function createMaterial(token:string,courseId:string,input:any){assertAllowedCourse(courseId);const body:any={title:input.title,description:input.description,state:input.state??"DRAFT",topicId:input.topicId,materials:links(input.links),scheduledTime:input.scheduledTime};Object.keys(body).forEach(k=>body[k]===undefined&&delete body[k]);return api<any>(token,`/courses/${encodeURIComponent(courseId)}/courseWorkMaterials`,{method:"POST",body:JSON.stringify(body)});}
export async function createAnnouncement(token:string,courseId:string,input:any){assertAllowedCourse(courseId);const body:any={text:input.text,state:input.state??"DRAFT",materials:links(input.links),scheduledTime:input.scheduledTime};Object.keys(body).forEach(k=>body[k]===undefined&&delete body[k]);return api<any>(token,`/courses/${encodeURIComponent(courseId)}/announcements`,{method:"POST",body:JSON.stringify(body)});}
export async function listSubmissions(token:string,courseId:string){assertAllowedCourse(courseId);const d=await api<any>(token,`/courses/${encodeURIComponent(courseId)}/courseWork/-/studentSubmissions?pageSize=100`);return d.studentSubmissions??[];}
