import { config, GOOGLE_SCOPES } from "./config";
export type GoogleTokens={access_token:string;expires_in:number;token_type:string;refresh_token?:string};
export type GoogleProfile={sub:string;email:string;email_verified?:boolean;name?:string};
export function buildGoogleAuthUrl(state:string){const u=new URL("https://accounts.google.com/o/oauth2/v2/auth");u.searchParams.set("client_id",config.googleClientId);u.searchParams.set("redirect_uri",config.googleCallbackUrl);u.searchParams.set("response_type","code");u.searchParams.set("scope",GOOGLE_SCOPES.join(" "));u.searchParams.set("state",state);u.searchParams.set("access_type","offline");u.searchParams.set("prompt","consent select_account");u.searchParams.set("include_granted_scopes","true");return u;}
async function tokenRequest(body:URLSearchParams):Promise<GoogleTokens>{const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body,cache:"no-store"});if(!r.ok)throw new Error(`google_token_error:${r.status}:${await r.text()}`);return r.json();}
export function exchangeGoogleCode(code:string){return tokenRequest(new URLSearchParams({code,client_id:config.googleClientId,client_secret:config.googleClientSecret,redirect_uri:config.googleCallbackUrl,grant_type:"authorization_code"}));}
export function refreshGoogleToken(refreshToken:string){return tokenRequest(new URLSearchParams({refresh_token:refreshToken,client_id:config.googleClientId,client_secret:config.googleClientSecret,grant_type:"refresh_token"}));}
export async function getGoogleProfile(accessToken:string):Promise<GoogleProfile>{const r=await fetch("https://openidconnect.googleapis.com/v1/userinfo",{headers:{Authorization:`Bearer ${accessToken}`},cache:"no-store"});if(!r.ok)throw new Error(`google_userinfo_error:${r.status}`);return r.json();}
export function assertAllowedGoogleAccount(profile:GoogleProfile){if(profile.email_verified!==true)throw new Error("google_email_not_verified");const allowed=config.allowedEmails;if(allowed.length&&!allowed.includes(profile.email.toLowerCase()))throw new Error(`google_account_not_allowed:${profile.email}`);}
