import { McpServer, type AuthInfo } from "@modelcontextprotocol/server"; import * as z from "zod/v4"; import { googleToken } from "./mcp-tokens"; import { listCourses,listTopics,createTopic,listCourseWork,createAssignment,createMaterial,createAnnouncement,listSubmissions } from "./classroom-api";
const readOnly={readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:true} as const; const writeSafe={readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:true} as const;
function ok(data:unknown){return{content:[{type:"text" as const,text:JSON.stringify(data)}],structuredContent:data as any};} function fail(error:unknown){return{content:[{type:"text" as const,text:error instanceof Error?error.message:String(error)}],isError:true};}
const Link=z.object({url:z.string().url(),title:z.string().optional()});
export function buildServer(auth?:AuthInfo){const server=new McpServer({name:"google-classroom-pablo",version:"0.1.0"});
server.registerTool("classroom_list_courses",{title:"List courses",description:"Lists active courses taught by the authenticated account.",inputSchema:z.object({}),annotations:readOnly},async()=>{try{return ok(await listCourses(googleToken(auth)))}catch(e){return fail(e)}});
server.registerTool("classroom_list_topics",{title:"List topics",description:"Lists topics in one allowed course.",inputSchema:z.object({courseId:z.string()}),annotations:readOnly},async({courseId})=>{try{return ok(await listTopics(googleToken(auth),courseId))}catch(e){return fail(e)}});
server.registerTool("classroom_create_topic",{title:"Create topic",description:"Creates a topic in one allowed course.",inputSchema:z.object({courseId:z.string(),name:z.string().min(1).max(200)}),annotations:writeSafe},async({courseId,name})=>{try{return ok(await createTopic(googleToken(auth),courseId,name))}catch(e){return fail(e)}});
server.registerTool("classroom_list_coursework",{title:"List coursework",description:"Lists coursework in one allowed course.",inputSchema:z.object({courseId:z.string()}),annotations:readOnly},async({courseId})=>{try{return ok(await listCourseWork(googleToken(auth),courseId))}catch(e){return fail(e)}});
server.registerTool("classroom_create_assignment",{title:"Create assignment",description:"Creates an assignment. Defaults to DRAFT.",inputSchema:z.object({courseId:z.string(),title:z.string().min(1).max(300),description:z.string().optional(),topicId:z.string().optional(),state:z.enum(["DRAFT","PUBLISHED"]).default("DRAFT"),maxPoints:z.number().min(0).max(1000).optional(),dueDate:z.object({year:z.number().int(),month:z.number().int().min(1).max(12),day:z.number().int().min(1).max(31)}).optional(),dueTime:z.object({hours:z.number().int().min(0).max(23),minutes:z.number().int().min(0).max(59)}).optional(),scheduledTime:z.string().datetime().optional(),links:z.array(Link).max(20).optional()}),annotations:writeSafe},async(input)=>{try{return ok(await createAssignment(googleToken(auth),input.courseId,input))}catch(e){return fail(e)}});
server.registerTool("classroom_create_material",{title:"Create material",description:"Creates a material post. Defaults to DRAFT.",inputSchema:z.object({courseId:z.string(),title:z.string().min(1).max(300),description:z.string().optional(),topicId:z.string().optional(),state:z.enum(["DRAFT","PUBLISHED"]).default("DRAFT"),scheduledTime:z.string().datetime().optional(),links:z.array(Link).max(20).optional()}),annotations:writeSafe},async(input)=>{try{return ok(await createMaterial(googleToken(auth),input.courseId,input))}catch(e){return fail(e)}});
server.registerTool("classroom_create_announcement",{title:"Create announcement",description:"Creates an announcement. Defaults to DRAFT.",inputSchema:z.object({courseId:z.string(),text:z.string().min(1).max(10000),state:z.enum(["DRAFT","PUBLISHED"]).default("DRAFT"),scheduledTime:z.string().datetime().optional(),links:z.array(Link).max(20).optional()}),annotations:writeSafe},async(input)=>{try{return ok(await createAnnouncement(googleToken(auth),input.courseId,input))}catch(e){return fail(e)}});
server.registerTool("classroom_list_submissions",{title:"List submissions",description:"Lists student submissions in one allowed course.",inputSchema:z.object({courseId:z.string()}),annotations:readOnly},async({courseId})=>{try{return ok(await listSubmissions(googleToken(auth),courseId))}catch(e){return fail(e)}});
return server;}
